server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: eagle-bank-api

  datasource:
    url: jdbc:h2:mem:eaglebank
    driver-class-name: org.h2.Driver
    username: sa
    password: password # Note: this would normally be secured and not hardcoded

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.eaglebank: DEBUG
    org.springframework.web: DEBUG